package sk.sb.training_assignment.entities;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import javax.persistence.*;
import java.io.Serializable;

/**
 * Entity class for address of a user.
 * Contains necessarty attributes and getters and setters for them.
 * @author <a href="https://github.com/DavidZimen">Dávic Zimen</a>
 */
@Entity
@Table(name = "TA_ADDRESS")
@Getter @Setter @NoArgsConstructor
public class Address implements Serializable {

//ATTRIBUTES
    /**
     * Unique identifier for address.
     * Automatically generated by Hibernare.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long id;

    /**
     * Street name for address.
     */
    @Column(name = "street")
    private String street;

    /**
     * House number of user living on this address.
     */
    @Column(name = "houseNumber")
    private int houseNumber;

    /**
     * City where the address is located.
     */
    @Column(name = "city")
    private String city;

    /**
     * User that lives on this address.
     */
    @OneToOne(mappedBy = "address")
    @JsonBackReference
    private User user;

    /**
     * Parametric constructor to make the address.
     * @param pStreet Street name.
     * @param pHouseNumber House number.
     * @param pCity City of the address.
     */
    public Address(String pStreet, int pHouseNumber, String pCity) {
        this.city = pCity;
        this.street = pStreet;
        this.houseNumber = pHouseNumber;
    }
}
